version: '3.6'

services:
  nginx:
    image: localhost:5000/inspire-portal:latest
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - ./portal-pgi/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../cert/bundle.pem:/cert/bundle.pem
      - ../cert/pgigovpl.key:/cert/priv.key
    ports:
      - 9443:443
      - 9080:80
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 1s
        failure_action: continue
        monitor: 120s
        max_failure_ratio: 0.3

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 20s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 1s
        failure_action: continue
        monitor: 120s
        max_failure_ratio: 0.3

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 1s
        failure_action: continue
        monitor: 120s
        max_failure_ratio: 0.3

  flower:
    image: mher/flower:1.2
    restart: always
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq:5672//
      - FLOWER_PORT=5555
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 1s
        failure_action: continue
        monitor: 120s
        max_failure_ratio: 0.3

  workers:
    image: localhost:5000/inspire-validator:latest
    command: Workers
    restart: always
    environment:
      # common
      - LOG_LEVEL=20
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - RESULT_SERIALIZER=pickle
      - TASK_SERIALIZER=pickle
      - ACCEPT_CONTENT=["pickle","json"]
      # celery workers
      - CELERY_WORKERS=9
      - IMPORTS=["src.tasks"]
      - BROKER_HEARTBEAT=120
      - CELERY_CONSUME_QUEUES=["celery"]
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 1s
        failure_action: continue
        monitor: 120s
        max_failure_ratio: 0.3

  restapi:
    image: localhost:5000/inspire-validator:latest
    command: RestApi
    restart: always
    environment:
      # common
      - LOG_LEVEL=20
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - RESULT_SERIALIZER=pickle
      - TASK_SERIALIZER=pickle
      - ACCEPT_CONTENT=["pickle","json"]
      # restapi
      - REST_HOST=0.0.0.0
      - REST_PORT=5000
      - REST_WORKERS=2
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 1s
        failure_action: continue
        monitor: 120s
        max_failure_ratio: 0.3

networks:
  default:
    attachable: True

