version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: pgi-portal-nginx
    ports:
      - "8060:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./../static/portal.json:/usr/share/nginx/html/portal-pgi/assets/portal.json:z
    restart: unless-stopped

